HdrHistogram/HdrHistogram_c

src/hdr_time.h
CLOCK_REALTIME can jump forwards and backwards so it's not useful for
measuring elapsed time. Switch to CLOCK_MONOTONIC instead which is
guaranteed to increase monotonically.
Signed-off-by: Pekka Enberg <penberg@iki.fi>
=> Use CLOCK_MONOTONIC for hdr_time()

src/hdr_histogram.c, src/hdr_histogram.h
This is primarily to support the Rust binding I wrote (since Rust is much more particular about mutability than C), but it seems like its generally useful to know which functions cause changes and which are read-only.
=> Constify hdr_histogram parameters where possible.

src/hdr_writer_reader_phaser.c
Adding missing include stdint.h in hdr_writer_reader_phaser.c
=> Fixing compilation on Linux64bit - Clang 3.5.0

src/hdr_encoding.c, src/hdr_encoding.h, src/hdr_histogram_log.c
So, in cases where b64 is linked in - the symbols will
conflict with this hdr histogram library.
Prefix the base64 code with hdr_ to just avoid the conflict
on static links.
=> encoding: histogram encoding conflicts with b64 library

CMakeLists.txt, examples/hiccup.c, src/hdr_encoding.c, src/hdr_histogram.c, src/hdr_histogram_log.c, src/hdr_tests.h, src/hdr_writer_reader_phaser.c, test/hdr_histogram_log_test.c, test/hdr_histogram_perf.c, test/hdr_histogram_test.c, test/minunit.h
I'm used to building with more warnings and sometimes need to compile with older compilers as well.
=> Allow STD C89 build and be more strict about warnings

src/hdr_writer_reader_phaser.h
`#include <hdr_thread.h>` relies on hdr_thread.h being in the include path (ie, `.`), but `"hdr_thread.h"` looks in the same dir as the includer regardless.
=> Use local include for hdr_thread.h

CMakeLists.txt, src/CMakeLists.txt
First commit honors LIB_SUFFIX, which is mandatory for distribution using /usr/lib64
Second introduce soname version, which is mandatory for API/ABI compatibility tracking.
Of course, this means ABI have to be tracked in future release, and those value be  fixed.
=> Add missing soname / version

CMakeLists.txt
Use CMAKE_CURRENT_SOURCE_DIR rather than CMAKE_SOURCE_DIR so an
enclosing cmake project can use us via add_subdirectory().
=> build: allow inclusion into cmake projects via add_subdirectory()

src/CMakeLists.txt
Added ability to avoid use `include_directories` in case of build HdrHistogram_c as sub-project in CMake based project.
Example:
```
add_subdirectory(deps/HdrHistogram_c)
...
add_executable(app main.cpp)
target_link_libraries(app hdr_histogram_static)
```
at this point you don't need `include_directories(deps/HdrHistogram_c/src)`
Thanks
=> Improved cmake script

examples/hiccup.c, src/hdr_time.c, src/hdr_time.h
This code adds a new function, hdr_getnow which uses (on Linux) the CLOCK_REALTIME clock.
The hdr_gettime uses CLOCK_MONOTONIC, which relies on an unspecified point in time for its initial representation. Therefore, it is not suitable to find the actual point in time, since it may represent elapsed time since boot or others instead of Epoch.
=> Use a different clock to obtain the start time

src/hdr_histogram.h, src/hdr_thread.h, test/CMakeLists.txt, test/minunit.c, test/minunit.h
I've seen compilation warnings on linux/osx when using this in C++, due to the zero length array. In addition, building the project causes some compilation warnings which i've also resolved.
I'm tidying up warnings as I want to use it in a 'warnings as errors' project. Hopefully these aren't contentious. The inline keyword is C99, so I wasn't sure if you were supporting earlier compilers.
Looks like inline is a step too far on windows, so i've removed it
=> Some small changes

test/hdr_histogram_perf.c
I was seeing a build warning on linux/gcc about the use of the tick (') numeric formatter, so this implementation gives the same style output (thousand separators) but avoids the warning. It is cross platform and so removes the special windows code path which is nice.
The included function is a little specific (it won't work for negatives, and has the 2dps 'baked in'), but it was the simplest I could think of to give the same format.
An alternative would be to just drop the comma separated output, and revert to '%0.2f' for the numeric format, but keeping the output the same may be useful so I went with this option.
As this is a test app, the impact should be pretty low.
=> Modified performance test to avoid unsupported tick (') format

src/hdr_interval_recorder.c, src/hdr_writer_reader_phaser.c, src/hdr_writer_reader_phaser.h
The writer reader phaser allocates a mutex, which is not freed when it is destroyed.  This pull request fixes that and also fixes a typo in the destructor function's name.
=> Hdr writer reader phaser leak fix

src/hdr_histogram_log.c
Both the source and destination of the parameter are const, so cast to a const.
This fixes a compiler warning on modern clang.
Signed-off-by: Phil Wise <phil@advancedtelematic.com>
=> Fix const-ness of casts

examples/hiccup.c, src/hdr_interval_recorder.c
Address sanitiser revealed a memory leak in hdr_interval_recorder. The leak was a consequence of using free instead of hdr_close in the hdr_interval_recorder_destroy function.
In addition, the active and inactive pointers should be set to null during hdr_interval_recorder initialisation.
=> Fix leak in hdr_interval_recorder

src/hdr_histogram.h
The original comment that the `hdr_histogram` can be released via `free` is misleading and it is only for older versions.
Update the comment to suggest using `hdr_close` to release the histogram.
=> Fixed the misleading comment on the hdr_init

README.md
It was linking to the image instead of build log page.
=> docs: fix appveyor badge in README

src/hdr_histogram.c, src/hdr_histogram_log.c
These typecasts are needed in order to avoid warnings when compiling with a c++ compiler.
Implicit typecasts from void* is allowed in C but not in C++.
=> Fix c++ warnings

CMakeLists.txt
Hello there, working on a package for Fedora. We build all software with bunch of flags however the way the makefile is structured today does not allow redefinition of compiler and linker flags cleanly. This fixes it.
=> Allow flags to be redefined

src/hdr_histogram.c
hdr_close() will segfault if it is passed a null pointer.  Typically, free()-like functions handle
"freeing an allocation that was never allocated" as a no-op, rather than erroring or crashing..  Otherwise, the caller has to be responsible to check themselves with every invocation.
This patch gates dereferencing `h` in order to free its members by first ensuring that `h`
itself is non-null.
=> hdr_close(): no-op if pointer is null

src/hdr_time.c
OpenBSD supports clock_gettime() as it's used for Linux. Add macro test enabling clock_gettime() use on OpenBSD.
=> Add support for OpenBSD

src/CMakeLists.txt
Add `HDR_HISTOGRAM_BUILD_SHARED` and `HDR_HISTOGRAM_INSTALL_STATIC` options
Context: in downstream distribution (RPM packages), common practices is to no package the static libraries, as shared is always preferred.
But we need to build them to also build and run the test suite.
=> add options to be able to not install libraries

src/CMakeLists.txt
Sorry for this error in my previous (merged) pr #84
=> fix copy/paste issue in macro name

src/CMakeLists.txt
On Windows, HdrHistogram installs dll file (if shared) in lib folder while it should go to bin folder. It's fixed in this PR.
=> Fix installation folder for runtime

src/hdr_histogram.c, src/hdr_histogram.h, test/hdr_histogram_benchmark.cpp, test/hdr_histogram_test.c
Thinking on the way we do latency percentile analysis, we normally require more than one percentile to be calculated for the given histogram at any given moment (example of p50, p95, p99, p999). 
If you look at the C function that provides the percentile calculation implementation you'll notice that we iterate over the counts array starting from 0 up until the we've reached a cumulative count of samples that represents or surpasses the requested percentile. 
By profiling `hdr_value_at_percentile` symbol and annotate it we'll notice that 99% of the CPU cycles of `hdr_value_at_percentile` are spent on the iterator calculating the cumulative count up until we reach or surpass the count that represents the percentile.
This means that if we want to compute p50 and p99, we could re-use the …
=> Added new API hdr_value_at_percentiles() as a means for redudant computation removal

src/hdr_histogram.c, src/hdr_histogram_log.c, src/hdr_interval_recorder.c, src/hdr_malloc.h, src/hdr_thread.c, src/hdr_writer_reader_phaser.c
This PR adds the ability to change the HdrHistogram allocator at compile time. 
The `hdr_malloc.h`  file is used in order to change the HdrHistogram allocator at compile time.
To alter the allocator just alter the following defines to what you want to use in `hdr_malloc.h`
```
#define hdr_malloc malloc
#define hdr_calloc calloc
#define hdr_realloc realloc
#define hdr_free free
```
Also add the include of your alternate allocator if needed (not needed in order to use the default libc allocator).
=> Add the ability to change the HdrHistogram allocator at compile time.

CMakeLists.txt, hdr_histogram.pc.in
This like breaks pkg-config usage on same old version (pkgconfig 0.27 on RHEL-7) and is not used
=> Clean pkgconfig

CMakeLists.txt, cmake/JoinPaths.cmake, hdr_histogram.pc.in
In order to handle cross compilation and other concerns, pkg-config files support defining includedir/libdir relative to prefix and perform deferred expansion. For this reason, the expected value of each is:
```
${prefix}/lib
${prefix}/include
```
or similar.
This may or may not work depending on how the standard directories are installed:
- autotools
all directory variables must be specified by absolute path. However, those variables use the same format as pkg-config to do expansions, so it is possible to pass `--libdir='${prefix}/lib'` and generate correct pkg-config files
- meson
all directory variables can be specified by either relative or absolute path. For absolute paths, if they fit inside prefix they are converted to relative paths. There is also a builtin `join_paths` function …
=> pkg-config file: fix handling of variable-relative paths

include/hdr/hdr_interval_recorder.h
=> hdr_interval_recorder.h: fix typos in function documentation

src/hdr_histogram.c, test/hdr_histogram_benchmark.cpp
This is basically a C port of the optimization in PR https://github.com/HdrHistogram/hdrhistogram-go/pull/48 by @filipecosta90.
before:
```
yoav@yoav-thinkpad:~/HdrHistogram_c/build$ ./test/hdr_histogram_benchmark --benchmark_filter=BM_hdr_value_at_percentile/3/86400000 --benchmark_min_time=10
2022-03-21 12:41:46
Running ./test/hdr_histogram_benchmark
Run on (12 X 4600 MHz CPU s)
CPU Caches:
L1 Data 32K (x6)
L1 Instruction 32K (x6)
L2 Unified 256K (x6)
L3 Unified 12288K (x1)
Load Average: 0.68, 0.81, 0.89
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
-----------------------------------------------------------------------------------
Benchmark …
```
=> `hdr_value_at_percentile` optimization.

src/hdr_histogram_log.c
The fuzzer from https://github.com/HdrHistogram/HdrHistogram_c/pull/120 found some leaks when the `hdr_decode_compressed*` functions call `hdr_init` but later fails and cleans up `h` by way of `hdr_free(h)`. The problem is that the `counts` field on the histogram is leaked, which is allocated here:
https://github.com/HdrHistogram/HdrHistogram_c/blob/8dcce8f68512fca460b171bccc3a5afce0048779/src/hdr_histogram.c#L424 and assigned to the `counts` field here:
https://github.com/HdrHistogram/HdrHistogram_c/blob/8dcce8f68512fca460b171bccc3a5afce0048779/src/hdr_histogram.c#L437
Instead of using `hdr_free` the cleanup function should be `hdr_close: https://github.com/HdrHistogram/HdrHistogram_c/blob/8dcce8f68512fca460b171bccc3a5afce0048779/src/hdr_histogram.c#L445-L451
=> hdr_historgram_log: fix 3 memory leaks on histogram-counts

.clusterfuzzlite/Dockerfile, .clusterfuzzlite/README.md, .clusterfuzzlite/build.sh, .clusterfuzzlite/log_reader_fuzzer.c, .clusterfuzzlite/project.yaml, .github/workflows/cflite_pr.yml
This adds fuzzing by way of
[ClusterFuzzLite](https://google.github.io/clusterfuzzlite/), which is a GitHub action that will perform a short amount of fuzzing for new PRs. The goal is to use fuzzing to catch bugs that may be introduced by new PRs.
=> Add fuzzing by way of ClusterFuzzLite
